---
- name: add nodejs GPG key into apt
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present
  tags:
    - nodejs_create

- name: add nodejs repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{nodejs_version}} wheezy main"
    state: present
  tags:
    - nodejs_create

- name: install nodejs package
  apt:
    pkg: nodejs
    update-cache: yes
  tags:
    - nodejs_create
